const fs=require('fs');
const pages={
'varmepumpar.html':{title:'Värmepumpar',lead:'Rätt dimensionerad värme som sänker energikostnaden och höjer komforten.',intro:'Vi hjälper villaägare, företag och fastighetsägare från förstudie till driftsatt anläggning. Varje lösning dimensioneras efter byggnaden – inte efter en standardmall.',bullets:['Bergvärme, luft/vatten och frånluft','Dimensionering och energikalkyl','Installation, injustering och service'],img:'hero.png'},
'vvs-installation.html':{title:'VVS-installation',lead:'Hållbara installationer för nybyggnation, renovering och ombyggnad.',intro:'Från stambyten och tappvatten till kompletta värmesystem. Vi planerar arbetet med tydliga gränsdragningar och dokumenterar installationen för framtida förvaltning.',bullets:['Tappvatten och avlopp','Radiatorer och golvvärme','Teknikrum och undercentraler'],img:'craft.png'},
'service.html':{title:'Service & underhåll',lead:'Snabb felsökning och förebyggande underhåll som minskar avbrotten.',intro:'Våra servicetekniker hjälper till vid akuta fel och planerade kontroller. För återkommande behov erbjuder vi serviceavtal med tydlig historik och prioriterad hjälp.',bullets:['Felsökning och reparation','Planerade funktionskontroller','Serviceavtal för fastigheter och företag'],img:'craft.png'},
'badrum.html':{title:'Badrum',lead:'Trygga våtrumsinstallationer där funktion, kvalitet och uttryck hänger ihop.',intro:'Vi utför VVS-delen i badrumsrenoveringar och samordnar gärna arbetet med övriga yrkesgrupper. Du får en tydlig offert och dokumentation på utfört arbete.',bullets:['Kompletta VVS-arbeten i badrum','Montering av inredning och porslin','Samordning med bygg och el'],img:'hero.png'},
'energioptimering.html':{title:'Energioptimering',lead:'Få ut mer av befintliga system innan du investerar i nya.',intro:'Vi analyserar temperaturer, flöden, styrning och driftmönster. Ofta finns betydande besparingar i en bättre injusterad anläggning.',bullets:['Energikartläggning','Injustering och styrning','Åtgärdsplan med prioriteringar'],img:'craft.png'},
'privatperson.html':{title:'För dig som privatperson',lead:'En kunnig kontakt från första fråga till färdig installation.',intro:'Vi hjälper dig att göra rätt val för huset, ekonomin och vardagen. Du får raka svar, fasta hållpunkter och hantverkare som tar hand om hemmet.',bullets:['Kostnadsfritt första samtal','Tydlig offert och tidplan','ROT-underlag och dokumentation'],img:'hero.png'},
'fastighetsagare.html':{title:'För fastighetsägare',lead:'Stabil drift, korta ledtider och kontroll över hela beståndet.',intro:'Vi fungerar som långsiktig VVS-partner för bostadsrättsföreningar och fastighetsbolag – från daglig service till planerade energi- och renoveringsprojekt.',bullets:['Felanmälan och serviceavtal','Underhållsplanering','Energi- och systemoptimering'],img:'team.png'},
'byggforetag.html':{title:'För byggföretag',lead:'En installationspartner som håller tempo, kvalitet och dialog.',intro:'Vi går in tidigt, upptäcker kollisioner och levererar enligt gemensam produktionsplan. ÄTA-hantering och egenkontroller är tydliga från start.',bullets:['Kalkyl och projekteringsstöd','Produktion och samordning','Egenkontroll och överlämning'],img:'team.png'},
'foretag.html':{title:'För företag',lead:'VVS-lösningar som låter verksamheten fortsätta utan onödiga stopp.',intro:'Vi planerar installationer och service efter era öppettider, flöden och krav. Passar kontor, handel, verkstad och mindre industrimiljöer.',bullets:['Lokalanpassningar','Akut och planerad service','Ventil- och värmesystem'],img:'craft.png'},
'vart-team.html':{title:'Vårt team',lead:'Yrkesstolthet, omtanke och tydligt ansvar i varje uppdrag.',intro:'Nordform är ett fiktivt demoföretag. Personerna nedan är därför exempelroller och bilden är AI-genererad – perfekt för att visa hur en riktig teamsida kan byggas.',bullets:['Projektledning','Certifierade montörer','Service och kundansvar'],img:'team.png'},
'jobba-med-oss.html':{title:'Jobba med oss',lead:'För dig som vill göra hantverk med både precision och personlighet.',intro:'I den här demon visar vi hur en karriärsida kan presentera kultur, utveckling och lediga roller utan att bli opersonlig.',bullets:['Modern utrustning och tydliga processer','Kompetensutveckling','Litet lag med stort ansvar'],img:'team.png'},
'certifikat.html':{title:'Kvalitet & certifikat',lead:'Spårbart arbete och dokumentation som håller hela vägen.',intro:'Detta är exempel på hur behörigheter, kvalitetssystem och garantier kan beskrivas. Byt alltid till det verkliga företagets aktuella certifikat före publicering.',bullets:['Säker Vatten – exempelplats','Egenkontroller per uppdrag','Dokumenterad överlämning'],img:'craft.png'},
'vvs-i-linkoping.html':{title:'VVS i Linköping',lead:'Lokal VVS-service för hem, företag och fastigheter i Linköpingsområdet.',intro:'En exempelbyggd lokal landningssida med unik, relevant information – tänkt som mall för ett riktigt verksamhetsområde.',bullets:['Service med lokala inställelsetider','Installation och värmepumpar','Tydlig bokning och offert'],img:'hero.png'},
'vvs-i-motala.html':{title:'VVS i Motala',lead:'Trygga installationer och service för hela Motalaregionen.',intro:'Sidan visar hur en lokal tjänstesida kan vara hjälpsam för besökaren utan att bara upprepa samma sökord.',bullets:['Villa och fastighet','Värme och vatten','Planerad service'],img:'team.png'},
'vvs-i-mjolby.html':{title:'VVS i Mjölby',lead:'Energieffektiva VVS-lösningar med en tydlig kontakt genom projektet.',intro:'Anpassa texten till verklig lokal närvaro, referenser och erbjudanden innan en kundsida publiceras.',bullets:['Rådgivning och offert','Installation och dokumentation','Service efter avslutat projekt'],img:'craft.png'}
};
const nav=`<div class="topnote">Demowebbplats · Fiktivt företag</div><header class="site-header"><div class="wrap nav"><a class="brand" href="index.html"><span class="brand-mark"></span><span>NORDFORM<small>VVS & ENERGI</small></span></a><button class="menu" aria-label="Öppna meny" aria-expanded="false">☰</button><nav class="navlinks"><a href="tjanster.html">Tjänster</a><a href="referenser.html">Referenser</a><a href="om-oss.html">Om oss</a><a href="kontakt.html">Kontakt</a></nav><a class="nav-cta" href="kontakt.html">Be om offert →</a></div></header>`;
const foot=`<section class="cta"><div class="wrap"><div><span class="eyebrow" style="color:#fff">Nästa steg</span><h2>Vad behöver du hjälp med?</h2></div><a class="button" href="kontakt.html">Berätta om uppdraget →</a></div></section><footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark"></span><span>NORDFORM<small>VVS & ENERGI</small></span></a><p style="max-width:420px;margin-top:20px">En fiktiv demowebbplats för ett modernt installationsföretag. Alla namn, kontaktuppgifter och kundcase är exempel.</p></div><div><h3>Utforska</h3><a href="tjanster.html">Tjänster</a><a href="referenser.html">Referenser</a><a href="om-oss.html">Om oss</a><a href="kontakt.html">Kontakt</a></div><div><h3>Demo-kontakt</h3><a href="tel:+46100000000">010-000 00 00</a><a href="mailto:hej@nordform-demo.se">hej@nordform-demo.se</a><p>Industrivägen 12<br>Exempelstad</p></div></div><div class="legal"><span>© 2026 Nordform Demo</span><span>Fiktivt företag · Ej kommersiell verksamhet</span></div></div></footer><script src="script.js"></script>`;
for(const [file,p] of Object.entries(pages)){const cards=Object.entries(pages).filter(([f])=>['varmepumpar.html','service.html','energioptimering.html'].includes(f)&&f!==file).slice(0,2).map(([f,x],i)=>`<a class="card" href="${f}"><span class="card-num">0${i+1}</span><h3>${x.title}</h3><p>${x.lead}</p><span class="arrow">Läs mer →</span></a>`).join('');const html=`<!doctype html><html lang="sv"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.title} | Nordform VVS & Energi</title><meta name="description" content="${p.lead}"><link rel="stylesheet" href="styles.css"></head><body>${nav}<main><section class="page-hero"><div class="wrap"><div class="breadcrumb"><a href="index.html">Start</a> / ${p.title}</div><h1>${p.title}</h1><p>${p.lead}</p></div></section><section class="section"><div class="wrap content-grid"><article class="prose"><p class="eyebrow">Så hjälper vi dig</p><h2>Genomtänkt från första samtalet.</h2><p>${p.intro}</p><img class="service-visual" src="assets/${p.img}" alt="Illustrativ miljöbild för ${p.title.toLowerCase()}"><h2>Det här ingår</h2><ul>${p.bullets.map(x=>`<li>${x}</li>`).join('')}</ul><h3>En trygg arbetsgång</h3><p>Vi börjar med behov och förutsättningar, återkommer med tydligt förslag och planerar arbetet tillsammans. Efter utfört uppdrag går vi igenom funktion, dokumentation och nästa rekommenderade steg.</p></article><aside class="aside"><span class="eyebrow">Snabbvägar</span><a href="tjanster.html">Alla tjänster</a><a href="referenser.html">Se exempelprojekt</a><a href="kontakt.html">Be om offert</a><a href="tel:+46100000000">Ring 010-000 00 00</a><p class="form-note" style="margin-top:20px">Observera: kontaktuppgifterna tillhör ett fiktivt demoföretag.</p></aside></div></section>${cards?`<section class="section soft"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Mer från Nordform</span><h2>Relaterade områden</h2></div></div><div class="cards">${cards}</div></div></section>`:''}</main>${foot}</body></html>`;fs.writeFileSync(file,html)}
